<?xml version="1.0"?>
<xs:schema xml:id="root"
	   xmlns:xs="http://www.w3.org/2001/XMLSchema"
	   xmlns:acrn="https://projectacrn.org">

  <xs:assert test="count(/acrn-config/vm[vm_type = 'SERVICE_VM']) &lt; 2">
    <xs:annotation acrn:severity="error">
      <xs:documentation>There can be at most 1 service VM.</xs:documentation>
    </xs:annotation>
  </xs:assert>

  <xs:assert test="every $pre_vm in /acrn-config/vm[starts-with(vm_type, 'PRE')] satisfies
                   every $svm in /acrn-config/vm[vm_type = 'SERVICE_VM'] satisfies
                   $pre_vm/@id &lt; $svm/@id">
    <xs:annotation acrn:severity="error">
      <xs:documentation>The pre-launched VM (ID: {$pre_vm/@id}) shall not have a larger VM ID than the service VM (ID: {$svm/@id}).</xs:documentation>
    </xs:annotation>
  </xs:assert>

  <xs:assert test="every $post_vm in /acrn-config/vm[starts-with(vm_type, 'POST')] satisfies
                   every $svm in /acrn-config/vm[vm_type = 'SERVICE_VM'] satisfies
                   $post_vm/@id &gt; $svm/@id">
    <xs:annotation acrn:severity="error">
      <xs:documentation>The post-launched VM (ID: {$post_vm/@id}) shall not have a smaller ID than the service VM (ID: {$svm/@id}).</xs:documentation>
    </xs:annotation>
  </xs:assert>

</xs:schema>
